export type VisualizationStatus = "available" | "planned";
export type ConceptField = "Computer Graphics" | "Signal Processing";

export type VisualizationMeta = {
  slug: string;
  number: string;
  title: string;
  shortTitle: string;
  summary: string;
  status: VisualizationStatus;
  field: ConceptField;
  topic: string;
  tags: string[];
  studyMinutes: number;
  difficulty: "Foundational" | "Intermediate";
  interaction: string;
  source: {
    title: string;
    pages: string;
  };
};

const sourceTitle = "Graphics & Visualization: Principles & Algorithms";
const signalSourceTitle = "Prerequisites: Signal Processing Reminder";

export const visualizations: VisualizationMeta[] = [
  {
    slug: "graphics-pipeline",
    number: "01",
    title: "Graphics Pipeline Map",
    shortTitle: "Render a Tiny Scene",
    summary: "Walk a triangle and quad from local vertices to projected fragments, one pipeline operation at a time.",
    status: "available",
    field: "Computer Graphics",
    topic: "Pipeline & Coordinates",
    tags: ["Coordinates", "Transforms", "Rendering"],
    studyMinutes: 14,
    difficulty: "Foundational",
    interaction: "Render two primitives",
    source: { title: sourceTitle, pages: "9-11" },
  },
  {
    slug: "clipping",
    number: "02",
    title: "Clipping Lab",
    shortTitle: "Clipping",
    summary: "Move geometry across a view boundary and watch valid fragments emerge.",
    status: "available",
    field: "Computer Graphics",
    topic: "Pipeline & Coordinates",
    tags: ["View volume", "Geometry", "Boundaries"],
    studyMinutes: 8,
    difficulty: "Foundational",
    interaction: "Move the primitive",
    source: { title: sourceTitle, pages: "12" },
  },
  {
    slug: "viewport-transform",
    number: "03",
    title: "Viewport Transform",
    shortTitle: "Viewport Transform",
    summary: "Map normalized coordinates into pixels through scale and translation.",
    status: "available",
    field: "Computer Graphics",
    topic: "Pipeline & Coordinates",
    tags: ["NDC", "Pixels", "Coordinates"],
    studyMinutes: 7,
    difficulty: "Foundational",
    interaction: "Map a point",
    source: { title: sourceTitle, pages: "13" },
  },
  {
    slug: "back-face-culling",
    number: "04",
    title: "Winding & Culling",
    shortTitle: "Winding & Culling",
    summary: "Reverse vertex order and see how orientation decides which faces survive.",
    status: "available",
    field: "Computer Graphics",
    topic: "Geometry & Models",
    tags: ["Triangles", "Orientation", "Meshes"],
    studyMinutes: 6,
    difficulty: "Foundational",
    interaction: "Reverse the winding",
    source: { title: sourceTitle, pages: "14" },
  },
  {
    slug: "rasterization",
    number: "05",
    title: "Rasterization Explorer",
    shortTitle: "Rasterization",
    summary: "Move a triangle across a pixel grid and watch primitives become fragments.",
    status: "available",
    field: "Computer Graphics",
    topic: "Rasterization & Visibility",
    tags: ["Pixels", "Triangles", "Sampling"],
    studyMinutes: 8,
    difficulty: "Foundational",
    interaction: "Drag the vertices",
    source: { title: sourceTitle, pages: "15-16" },
  },
  {
    slug: "depth-testing",
    number: "06",
    title: "Drawing Order vs. Depth",
    shortTitle: "Depth Testing",
    summary: "Compare painter-style drawing with a per-fragment depth buffer.",
    status: "available",
    field: "Computer Graphics",
    topic: "Rasterization & Visibility",
    tags: ["Z-buffer", "Occlusion", "Fragments"],
    studyMinutes: 9,
    difficulty: "Foundational",
    interaction: "Change a surface depth",
    source: { title: sourceTitle, pages: "17-19" },
  },
  {
    slug: "z-fighting",
    number: "07",
    title: "Z-Fighting Microscope",
    shortTitle: "Z-Fighting",
    summary: "Reveal how finite precision makes nearly coplanar surfaces compete.",
    status: "available",
    field: "Computer Graphics",
    topic: "Rasterization & Visibility",
    tags: ["Precision", "Z-buffer", "Artifacts"],
    studyMinutes: 9,
    difficulty: "Intermediate",
    interaction: "Inspect precision",
    source: { title: sourceTitle, pages: "20" },
  },
  {
    slug: "image-buffers",
    number: "08",
    title: "Image Buffer Workbench",
    shortTitle: "Image Buffers",
    summary: "Inspect pixel memory and compare grayscale, true-color, and palette encoding.",
    status: "available",
    field: "Computer Graphics",
    topic: "Images & Display",
    tags: ["Memory", "Color", "Encoding"],
    studyMinutes: 10,
    difficulty: "Foundational",
    interaction: "Change the encoding",
    source: { title: sourceTitle, pages: "21-23" },
  },
  {
    slug: "frame-timing",
    number: "09",
    title: "Frame Timing & Tearing",
    shortTitle: "Frame Timing",
    summary: "Scrub through scanout and see how buffering and timing affect the display.",
    status: "available",
    field: "Computer Graphics",
    topic: "Images & Display",
    tags: ["Framerate", "Buffers", "VSync"],
    studyMinutes: 9,
    difficulty: "Intermediate",
    interaction: "Change render time",
    source: { title: sourceTitle, pages: "24-27" },
  },
  {
    slug: "obj-mesh",
    number: "10",
    title: "OBJ Mesh Inspector",
    shortTitle: "OBJ Meshes",
    summary: "Connect vertex and face records to the geometry they describe.",
    status: "available",
    field: "Computer Graphics",
    topic: "Geometry & Models",
    tags: ["Meshes", "File formats", "Vertices"],
    studyMinutes: 8,
    difficulty: "Foundational",
    interaction: "Inspect the records",
    source: { title: sourceTitle, pages: "30" },
  },
  {
    slug: "digital-signals",
    number: "01",
    title: "From Continuous to Digital",
    shortTitle: "Digital Signals",
    summary: "Sample a continuous wave, reduce its amplitude levels, and measure what the digital representation loses.",
    status: "available",
    field: "Signal Processing",
    topic: "Signals & Sampling",
    tags: ["Sampling", "Quantization", "Digital signals"],
    studyMinutes: 10,
    difficulty: "Foundational",
    interaction: "Set rate and bit depth",
    source: { title: signalSourceTitle, pages: "5" },
  },
  {
    slug: "convolution",
    number: "02",
    title: "Convolution Workbench",
    shortTitle: "Convolution",
    summary: "Flip and shift an impulse response, multiply overlapping samples, and build the output one value at a time.",
    status: "available",
    field: "Signal Processing",
    topic: "Systems & Filters",
    tags: ["LTI systems", "Impulse response", "Convolution"],
    studyMinutes: 14,
    difficulty: "Intermediate",
    interaction: "Scrub the output index",
    source: { title: signalSourceTitle, pages: "6-13" },
  },
  {
    slug: "fir-iir-filters",
    number: "03",
    title: "FIR and IIR Filter Lab",
    shortTitle: "FIR & IIR Filters",
    summary: "Send the same signal through feedforward and feedback filters, then inspect their output and impulse response.",
    status: "available",
    field: "Signal Processing",
    topic: "Systems & Filters",
    tags: ["FIR", "IIR", "Stability"],
    studyMinutes: 13,
    difficulty: "Intermediate",
    interaction: "Change filter memory",
    source: { title: signalSourceTitle, pages: "14-17, 37" },
  },
  {
    slug: "sinusoid-anatomy",
    number: "04",
    title: "Sinusoid Anatomy",
    shortTitle: "Sinusoids",
    summary: "Connect amplitude, frequency, and phase to a waveform and the rotating complex number that generates it.",
    status: "available",
    field: "Signal Processing",
    topic: "Frequency Analysis",
    tags: ["Sinusoid", "Complex exponential", "Phase"],
    studyMinutes: 10,
    difficulty: "Foundational",
    interaction: "Shape the sinusoid",
    source: { title: signalSourceTitle, pages: "19-20" },
  },
  {
    slug: "transfer-functions",
    number: "05",
    title: "Transfer Function Explorer",
    shortTitle: "Transfer Functions",
    summary: "Probe a filter with one sinusoid and see how its frequency response changes amplitude and phase.",
    status: "available",
    field: "Signal Processing",
    topic: "Systems & Filters",
    tags: ["Frequency response", "Eigenfunction", "LTI systems"],
    studyMinutes: 12,
    difficulty: "Intermediate",
    interaction: "Sweep the frequency",
    source: { title: signalSourceTitle, pages: "21-25" },
  },
  {
    slug: "sampling-aliasing",
    number: "06",
    title: "Sampling and Aliasing Lab",
    shortTitle: "Sampling & Aliasing",
    summary: "Sample a tone above and below Nyquist, then compare the original with the lower frequency seen by the samples.",
    status: "available",
    field: "Signal Processing",
    topic: "Signals & Sampling",
    tags: ["Nyquist", "Aliasing", "Sample rate"],
    studyMinutes: 11,
    difficulty: "Intermediate",
    interaction: "Cross the Nyquist limit",
    source: { title: signalSourceTitle, pages: "31-34" },
  },
  {
    slug: "fourier-dft",
    number: "07",
    title: "Fourier and DFT Explorer",
    shortTitle: "Fourier & DFT",
    summary: "Mix two tones, compute their discrete spectrum, and expose leakage with a non-bin frequency and a window.",
    status: "available",
    field: "Signal Processing",
    topic: "Frequency Analysis",
    tags: ["Fourier transform", "DFT", "Windowing"],
    studyMinutes: 15,
    difficulty: "Intermediate",
    interaction: "Build and analyze a signal",
    source: { title: signalSourceTitle, pages: "23-31, 35-36" },
  },
];

export const availableCount = visualizations.filter(
  (visualization) => visualization.status === "available",
).length;

export const fields = Array.from(new Set(visualizations.map((item) => item.field)));
export const topics = Array.from(new Set(visualizations.map((item) => item.topic)));

export function getVisualization(slug: string) {
  return visualizations.find((item) => item.slug === slug);
}
